import { chromium } from '@playwright/test';
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 720, height: 450 } });
p.on('pageerror', (e) => console.log('pageerror', e.message));
await p.goto('http://localhost:5173/?shadows=0&fixedstep=1&dynres=0&quality=low&date=2026-01-14&hour=16&save=0');
await p.waitForFunction(() => window.__game?.ready, null, { timeout: 180000 });
const waitSim = (d) => p.evaluate((d) => new Promise((r) => { const t0 = window.__game.simTime(); const f = () => window.__game.simTime() - t0 >= d ? r() : requestAnimationFrame(f); f(); }), d);
console.log(await p.evaluate(() => window.__game.startActivity('kite')));
await p.locator('#game').click();
await p.keyboard.down('ArrowUp');
await waitSim(3);
await p.keyboard.up('ArrowUp');
await p.keyboard.down('ArrowLeft');
await waitSim(2);
await p.keyboard.up('ArrowLeft');
console.log(JSON.stringify(await p.evaluate(() => window.__game.activity())));
const pl = await p.evaluate(() => window.__game.player());
await p.evaluate(([x, y, z]) => window.__game.setView([x + 6, y + 3, z + 8], [x - 10, y + 40, z - 40]), pl);
await waitSim(0.2);
await p.screenshot({ path: '../shots/99-kites.png' });
await b.close();
